name: CI Build - Click

on:
  watch:
    types: [started]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
#    container:
#      image: accupara/aosp:latest
#     options: --user root
    permissions:
      contents: write
    steps:
      - name: Get the source code of this repositorie...
        uses: actions/checkout@v3

      - name: Get variable configuration...
        run: |
          echo "BUILD_TIME=$(TZ=Africa/Cairo date +%s | md5sum | awk '{print substr($1,1,10)}')" >> $GITHUB_ENV

      - name: Configuration Environment‌‌...
        run: |
          cd $GITHUB_WORKSPACE
          pwd
       #   sudo bash env.sh

      - name: Start KSU building...
        env:
           TELEGRAM_TOKEN: ${{ vars.TELEGRAM_TOKEN }}
        run: |
          cd $GITHUB_WORKSPACE
          echo "${{ secrets.TELEGRAM_TOKEN }}" >> $GITHUB_ENV
          sudo bash build.sh            #          sudo bash kernelsu.sh
          sudo chmod -R 0777 ./*
          echo "RELEASE_NAME=$(cat "$GITHUB_WORKSPACE/out/RELEASETITLE.txt")" >> $GITHUB_ENV
          echo "${{ env.RELEASE_NAME }}"

      - name: Upload to Release‌‌...
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ github.workspace }}/out/*"
          name: ${{ env.RELEASE_NAME }}
          tag: ${{ env.BUILD_TIME }}
          allowUpdates: true
          bodyFile: "${{ github.workspace }}/out/RELEASE.md"
          removeArtifacts: false
          replacesArtifacts: false
          token: ${{ secrets.GITHUB_TOKEN }}
